# Generated by Django 2.2.13 on 2020-06-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otl', '0006_qbank_question_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref',
            name='userfor',
        ),
    ]
