# Generated by Django 2.2.13 on 2020-06-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otl', '0007_remove_ref_userfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
    ]
